require('settings')
require('packer-config')
require('nvim-tree-config')
require('mappings')
require('lsp-config.language-server')
require('lsp-config.nvim-cmp')
require('lualine.lualine')
require('treesitter')
